dbconfigs:
  file-path: Data/bak
  configs:
    - func-name: "get_user"
      q-mode: "db"
      q-timeout: [5, 3]
      q-fallback: false
    - func-name: "ins_user_v1"
      always-write-file: false
    - func-name: "ins_log_activity_v1"
      always-write-file: false
    - func-name: "ins_class_v1"
      always-write-file: false
    - func-name: "get_class_v1"
      q-mode: "db"
      q-timeout: [5, 3]
      q-fallback: false
    - func-name: "get_user_v2"
      q-mode: "db"
      q-timeout: [5, 3]
      q-fallback: false